source: source
destination: site
excerpt_separator: ""
highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: redcarpet
permalink: /blog/:title
paginate: 10
paginate_path: "/page/:num/"
gems:
- jekyll-compass
- rouge
- jekyll-last-modified-at

redcarpet:
  extensions:
  - tables
  - autolink
